server:
  port: 8080
#  ssl:
#    protocol: TLS
#    key-store: classpath:server.keystore
#    key-store-password: 12345678
#    key-store-type: JKS
# spring config
http-port: 8080 # http重定向https配置
spring:
#  profiles:
#    active: dev # 激活指定的环境
  aop:
    auto: true
  jackson:
    time-zone: GMT+8
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
  # datasource config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jizhang?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: xienan605332935
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      auto-commit: true
      idle-timeout: 180000
      pool-name: VipHikariCP
      max-lifetime: 900000
      connection-timeout: 30000
      connection-test-query: select 1
  # redis配置
  redis:
    host: localhost
    port: 6379
    password: xienan123@
    database: 10
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml
  #如果有单独的mybatis配置，就可以将路径配置在ConfigLocation中

# 日志配置
logging:
  level:
    com.hgsoft.prepaid: info
    org.springframework: warn
    org.spring.springboot.dao: info
    org.apache.kafka: info
    com.xxl: info
    io.lettuce: info
    io.netty: info
    org.xnio: info
    com.zaxxer.hikari: info
    io.undertow: info
    org.apache.http: info
# 微信相关配置
wx:
  # 微信小程序相关配置
  mnp:
    appid: 2
    secret: 2
    message:
      url: https://api.weixin.qq.com/cgi-bin/message/subscribe/send?access_token=
      templateId:
        earlWarning: 1
        warning: 1

    # 微信支付相关配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql



weather:
  url: https://api.seniverse.com/v3/weather/now.json?key=%s&location=%s&language=zh-Hans&unit=c
  key: 1